on:
  push:
    paths:
      - .github/workflows/build.yml
      - server/**
  pull_request:
  workflow_dispatch:

jobs:
  build-server-python-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/build-push-action@v5
        with:
          context: server

  check-style-server-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: server
