on:
    push:
      branches:
        - main
      paths:
        - .github/workflows/build_pages.yml
        - api/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p site

      - uses: asyncapi/github-action-for-cli@v3.1.1
        with:
          command: generate
          filepath: api/asyncapi.yaml
          template: '@asyncapi/html-template@2.1.7'
          output: site

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-api-${{ github.sha }}
          path: site

  deploy:
    concurrency:
      group: github-pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-api-${{ github.sha }}
          path: site

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4
